Feature/members
Dev-incubator/DIMS.UI-12 pull request #2
Opened 2021-02-11 21:18 UTC by Larkgronick

Request date:
12/02/21

Total:
• Created members, members progress and members tasks pages
• Add drawer to navigate
• Implemented Router for these pages
• Realized own design

2021-02-13 08:10 UTC, maximsan requested changes
Hello, I left some comments, review them. Don't forget to rewrite your styles. Thanks!

2021-02-13 08:10 UTC, maximsan commented on src/components/Drawer/Drawer.jsx
> +      {menuItems.map((item) => (
spread item :)

2021-02-13 08:10 UTC, maximsan commented on src/config.js
> +// export const appLogo = process.env.REACT_APP_CUSTOM_LOGO;
remove

2021-02-13 08:10 UTC, maximsan commented on src/pages/Login.jsx
> +        <form className='input-fields' action=''>
remove action

2021-02-13 08:10 UTC, maximsan commented on src/pages/Login.jsx
> +          </button>
use Button component

2021-02-13 08:10 UTC, maximsan commented on src/pages/Main.jsx
> +      <Route path='/' component={() => <Login />} />
```<Route path='/' component={Login} />```

2021-02-13 08:10 UTC, maximsan commented on src/pages/Members.jsx
> +];
move constants to separate file

2021-02-13 09:05 UTC, YauhenKoipish commented on src/pages/Progress.jsx
> +        <span>{`(${ProgressBody.length})`}</span>
```suggestion
     <span>{ProgressBody.length}</span>
```
it looks better

2021-02-13 09:05 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +        <span>{`(${TasksBody.length})`}</span>
```suggestion
        <span>{TasksBody.length}</span>
```
it looks better

2021-02-13 09:05 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +          {menuItems.map((item) => (
spread item.

2021-02-13 09:05 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +  toggle: PropTypes.bool,
You need to use default value, at default props

2021-02-13 09:05 UTC, YauhenKoipish commented on src/pages/Progress.jsx
> +  toggle: PropTypes.bool.isRequired,
You need to use default value, at default props

2021-02-13 12:12 UTC, Larkgronick commented on src/App/App.jsx
> +export class App extends Component {
Changed, thanks

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Buttons/Button/Button.css
> +  --dev-color: #008f02;
Changed to scss variables

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Buttons/Hamburger/Hamburger.css
> +  width: 2em;
Changed to rem

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Buttons/Hamburger/Hamburger.css
> +  -ms-user-select: none;
Removed

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Buttons/Hamburger/Hamburger.css
> +  margin-top: -0.1em;
Changed to rem

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Buttons/Hamburger/Hamburger.jsx
> +    <button onClick={toggle} className={showDrawer ? 'bt-menu-trigger bt-menu-open' : 'bt-menu-trigger'} type='button'>
Moved to Button component and replaced class

2021-02-13 12:13 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +      {menuItems.map((item) => (
Changed, useful

2021-02-13 12:13 UTC, Larkgronick commented on src/config.js
> +// export const appLogo = process.env.REACT_APP_CUSTOM_LOGO;
Removed

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Login.jsx
> +        <form className='input-fields' action=''>
Removed

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Login.jsx
> +          </button>
Change both: register and login

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Main.jsx
> +      <Route path='/' component={() => <Login />} />
Changed

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Members.jsx
> +];
Moved to constants.js. Made for every component.

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Progress.jsx
> +          {menuItems.map((item) => (
Used spread for table rows

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Progress.jsx
> +        <span>{`(${ProgressBody.length})`}</span>
Here i need brackets - (3), your proposal makes only number - 3

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Tasks.jsx
> +        <span>{`(${TasksBody.length})`}</span>
Like in previous case i need brackets here

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Tasks.jsx
> +          {menuItems.map((item) => (
Changed

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Tasks.jsx
> +  toggle: PropTypes.bool,
Changed to isRequered here

2021-02-13 12:13 UTC, Larkgronick commented on src/pages/Progress.jsx
> +  toggle: PropTypes.bool.isRequired,
Here all is ok

2021-02-13 12:24 UTC, YauhenKoipish commented on src/pages/Progress.jsx
> +        <span>{`(${ProgressBody.length})`}</span>
```suggestion
     <span>({ProgressBody.length})</span>
```
it looks more simple

2021-02-13 12:24 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +        <span>{`(${TasksBody.length})`}</span>
```suggestion
     <span>({ProgressBody.length})</span>
```
it looks more simple

2021-02-13 12:26 UTC, YauhenKoipish commented on src/pages/Progress.jsx
> +  toggle: PropTypes.bool.isRequired,
default props is used for the default value, but you have no value

2021-02-13 12:46 UTC, YauhenKoipish approved these changes

2021-02-13 12:49 UTC, Larkgronick commented on src/pages/Tasks.jsx
> +        <span>{`(${TasksBody.length})`}</span>
Changed like in previous case

2021-02-13 12:49 UTC, Larkgronick commented on src/pages/Progress.jsx
> +        <span>{`(${ProgressBody.length})`}</span>
Yeah, thats much accurate, thanks. Changed in your way

2021-02-13 13:35 UTC, YauhenKoipish approved these changes

2021-02-14 12:14 UTC, maximsan approved these changes
Looks fine. I'm merging it.

2021-02-14 12:19 UTC, merged