Feature/validation
Dev-incubator/DIMS.UI-12 pull request #3
Opened 2021-02-26 14:55 UTC by Larkgronick

Request date:
26/02/21

Total:
• Resolve db errors
• Correct data view
• All pages bind together
• Fix render errors

2021-02-26 15:38 UTC, YauhenKoipish reviewed
looks good

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Buttons/Button/Button.jsx
> +  action: PropTypes.bool,
defaultProps action should be a function ( for example  action: ()=>{} )

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/MemberManager.jsx
> +    const { members, selected, edit } = this.props;
parse member[selected]

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +    const { tasks, selected, edit } = this.props;
parse task[selected]

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +    const isChecked = e.target.checked;
u can using parse 
```suggestion
const {name, chaced} = e.target
```

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +                {members.map((item) => (
spread item

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +  };
You are not saving changes to the state?

2021-02-26 15:38 UTC, YauhenKoipish commented on src/components/Popups/TaskTrackManager.jsx
> +    tasksToView[track].note[index].push(note);
you shouldn't change props

2021-02-26 15:38 UTC, YauhenKoipish commented on src/pages/Login.jsx
> +    // add check for incorrect input
delete it

2021-03-01 08:18 UTC, Larkgronick commented on src/components/Buttons/Button/Button.jsx
> +  action: PropTypes.bool,
Changed.

2021-03-01 08:18 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    const { members, selected, edit } = this.props;
Made refactor here, thanks.

2021-03-01 08:18 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const { tasks, selected, edit } = this.props;
Made refactor here.

2021-03-01 08:19 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const isChecked = e.target.checked;
Made refactor.

2021-03-01 08:19 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +                {members.map((item) => (
Spreaded, thanks.

2021-03-01 08:20 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +    tasksToView[track].note[index].push(note);
Refactor all task track behaviour.

2021-03-01 08:20 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +  };
Refactor all task track behaviour.

2021-03-01 08:20 UTC, Larkgronick commented on src/pages/Login.jsx
> +    // add check for incorrect input
It will be used in future validation feature.

2021-03-01 10:20 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +    }
u need to use setState

2021-03-01 10:20 UTC, YauhenKoipish commented on src/components/Popups/TaskTrackManager.jsx
> +  }
I'm not sure, but it might be better to use the componentDidMount to change the state when receiving data, and initialize the base state

2021-03-01 10:20 UTC, YauhenKoipish commented on src/pages/Main.jsx
> +  };
use setState, for state changes

2021-03-01 10:20 UTC, YauhenKoipish commented on src/pages/Main.jsx
> +    userTasks[track].date[userIndex].splice(subtaskIndex, 1);
use setState, for state changes

2021-03-01 10:20 UTC, YauhenKoipish commented on src/components/Popups/TaskTrackManager.jsx
> +    console.log(subtask);
you need to delete all console.log() before merge with main

2021-03-01 20:30 UTC, maximsan requested changes
Hello! I left some notes, basically you have the same top 5 mistake that you repeat everywhere. Don't forget to fix them in all components. I didn't repeat it every time only in several places. Thanks!

2021-03-01 20:30 UTC, maximsan commented on src/components/Buttons/Button/Button.jsx
> +  action: () => {},
we have noop helper in project for this :)

2021-03-01 20:30 UTC, maximsan commented on src/components/Buttons/Button/Button.jsx
> +  name: PropTypes.oneOfType([PropTypes.string, PropTypes.object]).isRequired,
name can be an object ? it's weird. I'd prefer to use `children` in component instead of `name` in this place, because it's more correct from React semantic

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
> +  }
It's better to move this logic to `ComponentDidMount()` life-cycle hook

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
> +            </label>
create you custom Input with label component

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
> +              </select>
create your custom select component

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
> +                }}
create a method

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +    }
We do not mutate state! Splice and push are banned method because of this. Change state with `useState` method

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +            </label>
create custom list with label component

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +                  saveData('tasks', this.state);
create a method

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
> +  }
You are correct. Nikita, please fit this and do not mutate the state. React do not track these changes properly.

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
> +            </label>
create custom textarea with label component

2021-03-01 20:30 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
> +                  closeEdit();
create a method

2021-03-01 20:30 UTC, maximsan commented on src/pages/Login.jsx
> +    // add check for incorrect input
@Larkgronick all comments should be marked as TODO: if you want to leave it. Especially if you do not want to get notes from reviewers about them.

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +    });
`closeEdit` can be used

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +    current.splice(selected, 1, value);
don't mutate data

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +    userTasks[track].note[userIndex].splice(subtask, 1, note);
don't mutate data, use `setState`

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +    userTasks[track].note[userIndex].push(note);
don't mutate data, use `setState`

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +    userTasks[track].date[userIndex].splice(subtaskIndex, 1);
don't mutate data, use `setState`

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +              selected={selected}
use React.Context, reduce your props, you have too many of them

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +              selected={selected}
use React.Context, reduce your props, you have too many of them

2021-03-01 20:30 UTC, maximsan commented on src/pages/Main.jsx
> +              edit={edit}
use React.Context, reduce your props, you have too many of them

2021-03-01 20:30 UTC, maximsan commented on src/pages/Members.jsx
> +                <td>
create your table component

2021-03-01 20:30 UTC, maximsan commented on src/pages/Members.jsx
> +                      editData(e);
create a method

2021-03-01 20:30 UTC, maximsan commented on src/services/helpers.js
> +}
all helper methods must be covered with unit-tests

2021-03-01 20:30 UTC, maximsan commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
remove it please, we use npm again because of the issues with travis CI/CD

2021-03-03 13:56 UTC, Larkgronick commented on src/pages/Login.jsx
> +    // add check for incorrect input
Marked as TO DO

2021-03-03 13:56 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    }
Created copy of state and used setState.

2021-03-03 13:56 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +  }
Moved to componentDidMount and used setState here and also for other Managers.

2021-03-03 13:57 UTC, Larkgronick commented on src/pages/Main.jsx
> +  };
Refactor here without ridect state update by using setState by the end of methods.

2021-03-03 13:57 UTC, Larkgronick commented on src/pages/Main.jsx
> +    userTasks[track].date[userIndex].splice(subtaskIndex, 1);
Removed this method. Its became unnecesary, because of my current changes in TaskTrack component.

2021-03-03 13:57 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +    console.log(subtask);
Sure, i removed it.

2021-03-03 13:57 UTC, Larkgronick commented on src/components/Buttons/Button/Button.jsx
> +  action: () => {},
Imported noop from 'shared' and replace default action.

2021-03-03 13:57 UTC, Larkgronick commented on src/components/Buttons/Button/Button.jsx
> +  name: PropTypes.oneOfType([PropTypes.string, PropTypes.object]).isRequired,
Used children prop and edit every Button Component in right way. Removed own created name prop.

2021-03-03 13:57 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +  }
Removed, created ComponentDidMount in similar places.

2021-03-03 13:58 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +            </label>
Created and replaced in all Manager Components.

2021-03-03 13:58 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +              </select>
Created Select component and used it in forms.

2021-03-03 13:59 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    }
Created copy and used setState method.

2021-03-03 13:59 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +            </label>
Created and implemented here.

2021-03-03 13:59 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +            </label>
Create Textarea component and impoted it here.

2021-03-04 12:02 UTC, YauhenKoipish submitted a review, later dismissed

2021-03-04 12:26 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +                }}
This method passed from Main component. I simplified it like this  action={saveData('members', this.state)}
It is enough?

2021-03-04 12:30 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +                  saveData('tasks', this.state);
Like in MembersManager this method passed from Main component. I need to create method inside TaskManager component and put  saveData('tasks', this.state) inside?

2021-03-04 14:59 UTC, Larkgronick commented on src/pages/Members.jsx
> +                <td>
Created and made full refactor for all tables.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +              selected={selected}
Used React.Context and removed multiprops inside Main component.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +              selected={selected}
Used React.Context and removed multiprops inside Main component.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +    userTasks[track].date[userIndex].splice(subtaskIndex, 1);
Changed this method.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +    userTasks[track].note[userIndex].push(note);
Changed this method.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +    userTasks[track].note[userIndex].splice(subtask, 1, note);
Changed this method.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +    current.splice(selected, 1, value);
Changed this method.

2021-03-04 15:00 UTC, Larkgronick commented on src/pages/Main.jsx
> +    });
Replaced.

2021-03-05 09:19 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +                  closeEdit();
Created.

2021-03-05 09:20 UTC, Larkgronick commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Removed.

2021-03-05 09:20 UTC, Larkgronick commented on src/services/helpers.js
> +}
Created helpers.test.jsx file with tests.

2021-03-05 10:16 UTC, Larkgronick commented on src/pages/Members.jsx
> +                      editData(e);
Created.

2021-03-05 10:17 UTC, Larkgronick commented on src/pages/Main.jsx
> +              edit={edit}
Used React.Context

2021-03-05 11:25 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +                }}
Put it here inside component using useContext.

2021-03-05 11:26 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +                  saveData('tasks', this.state);
Changed here using useContext.

2021-03-10 19:34 UTC, maximsan requested changes
Hello! Left several notes. Please, fix them. Thanks 👍🏻

2021-03-10 19:34 UTC, maximsan commented on src/components/FormElements/Input.jsx
> +        valueasdate={valueasdate}
Please, follow `camelCase` for new names

2021-03-10 19:34 UTC, maximsan commented on src/components/FormElements/List.jsx
> +          <li key={id} className={styles}>
Why does it not `className={className}` ?

2021-03-10 19:34 UTC, maximsan commented on src/components/FormElements/List.jsx
> +        {members.map(({ name: firstName, id, lastName }) => (
`members` should be `items` for general approach

2021-03-10 19:34 UTC, maximsan commented on src/components/FormElements/List.jsx
> +            <input defaultChecked={assigners.includes(id)} type='checkbox' value='true' name={id} onChange={action} />
`assigners` is also should be named in generic manner

2021-03-10 19:34 UTC, maximsan commented on src/components/FormElements/Textarea.jsx
> +      <textarea name={name} placeholder={placeholder} value={value} onChange={action} />
its' better to name `onChange={onChange}`

2021-03-10 19:34 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +      newStatus.splice(index, 1);
Can we don't use push and splice ?

2021-03-10 19:34 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +              action={(e) => this.saveAssigner(e)}
`action={this.saveAssigner}` - should be the same

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +  const context = useContext(MainContext);
get from props instead, don't use hooks

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +                    <Button action={(e) => showMemberData(e)} styles='button dev'>
action={showMemberData} should be the same

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +                    <Button action={(e) => showMemberData(e)} styles='button tasks'>
action={showMemberData} should be the same

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +                  <Button action={(e) => editMember(e)} styles='button edit'>
action={editMember} should be the same

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +                  <Button action={(e) => deleteMember(e)} styles='button danger'>
action={deleteMember} should be the same

2021-03-10 19:34 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
> +    const { userTasks, track } = this.props;
do in DidMount

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/TaskTrackTable.jsx
> +  const context = useContext(MainContext);
don't use hooks

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/TaskTrackTable.jsx
> +                  <Button action={(e) => deleteTrack(e)} styles='button danger'>
`action={deleteTrack}`

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/TasksTable.jsx
> +  const context = useContext(MainContext);
don't use hooks

2021-03-10 19:34 UTC, maximsan commented on src/components/Table/UserTasksTable.jsx
> +  const context = useContext(MainContext);
don't use hooks

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +    newState.splice(selected, 1, value);
`splice` !

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +    newState.push(value);
`push` !

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +    newUserTask[track].note[userIndex].splice(subtask, 1, note);
`splice` !

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +    newUserTask[track].note[userIndex].push(note);
`push` !

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +    newUserTask[track].date[userIndex].splice(subtaskIndex, 1);
`splice` !

2021-03-10 19:34 UTC, maximsan commented on src/pages/Main.jsx
> +          <Route path='/task-track' component={() => <TaskTrack />} />
`component={<TaskTrack />}`

2021-03-10 19:34 UTC, maximsan commented on src/services/helpers.test.jsx
> +});
Every test should follow `AAA` principle. It must have at least 1 - ok and 1 - fail tests. Please, fix it.

2021-03-11 09:20 UTC, Larkgronick commented on src/components/FormElements/Input.jsx
> +        valueasdate={valueasdate}
Changed valueasdate prop to valueAsDate.

2021-03-11 09:20 UTC, Larkgronick commented on src/components/FormElements/List.jsx
> +          <li key={id} className={styles}>
Replaced everywhere.

2021-03-11 09:29 UTC, Larkgronick commented on src/components/FormElements/List.jsx
> +        {members.map(({ name: firstName, id, lastName }) => (
Replaced.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/FormElements/List.jsx
> +            <input defaultChecked={assigners.includes(id)} type='checkbox' value='true' name={id} onChange={action} />
Replaced to 'elements'

2021-03-11 09:30 UTC, Larkgronick commented on src/components/FormElements/Textarea.jsx
> +      <textarea name={name} placeholder={placeholder} value={value} onChange={action} />
Changed 'action' to onChange in all forms. Also made similar replaces for Button with onClick.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +              action={(e) => this.saveAssigner(e)}
Thanks, good hint. Replaced.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +  const context = useContext(MainContext);
Removed useContext hook and passed methods from the props.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +                    <Button action={(e) => showMemberData(e)} styles='button dev'>
Replaced.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +                    <Button action={(e) => showMemberData(e)} styles='button tasks'>
Replaced.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +                  <Button action={(e) => editMember(e)} styles='button edit'>
Replaced.

2021-03-11 09:30 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +                  <Button action={(e) => deleteMember(e)} styles='button danger'>
Replaced.

2021-03-11 09:38 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +    const { userTasks, track } = this.props;
Moved to ComponentDidMount.

2021-03-11 09:39 UTC, Larkgronick commented on src/components/Table/TaskTrackTable.jsx
> +  const context = useContext(MainContext);
Removed unnecesary method.

2021-03-11 09:39 UTC, Larkgronick commented on src/components/Table/TaskTrackTable.jsx
> +                  <Button action={(e) => deleteTrack(e)} styles='button danger'>
Replaced.

2021-03-11 09:39 UTC, Larkgronick commented on src/components/Table/TasksTable.jsx
> +  const context = useContext(MainContext);
Removed useContext.

2021-03-11 09:39 UTC, Larkgronick commented on src/components/Table/UserTasksTable.jsx
> +  const context = useContext(MainContext);
Removed.

2021-03-12 11:40 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +      newStatus.splice(index, 1);
Removed here, and made refactor.

2021-03-12 11:41 UTC, Larkgronick commented on src/pages/Main.jsx
> +    newState.splice(selected, 1, value);
Changed to simple element save in array.

2021-03-12 11:41 UTC, Larkgronick commented on src/pages/Main.jsx
> +    newState.push(value);
Changed to concat.

2021-03-12 11:42 UTC, Larkgronick commented on src/pages/Main.jsx
> +    newUserTask[track].note[userIndex].splice(subtask, 1, note);
Changed to direct element saving.

2021-03-12 11:42 UTC, Larkgronick commented on src/pages/Main.jsx
> +    newUserTask[track].note[userIndex].push(note);
Changed to concat.

2021-03-12 11:43 UTC, Larkgronick commented on src/pages/Main.jsx
> +    newUserTask[track].date[userIndex].splice(subtaskIndex, 1);
Changed to slice.

2021-03-12 11:43 UTC, Larkgronick commented on src/pages/Main.jsx
> +          <Route path='/members' component={() => <Members />} />
Changed as in previous cases.

2021-03-12 11:43 UTC, Larkgronick commented on src/pages/Main.jsx
> +          <Route path='/task-track' component={() => <TaskTrack />} />
Changed as in previous cases.

2021-03-12 16:47 UTC, YauhenKoipish submitted a review, later dismissed

2021-03-15 20:13 UTC, maximsan requested changes
Hello. It's better than previously, but we still have what to improve. I left comments, please fix them. Thanks!

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  results.roleErr = validateField('role', role);
maybe you can simplify it ? create an array, map through... and write `validateField...` once. 
the same in other methods below.

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  return value.length === 0;
`!value.length`

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  const belarusNumber = /^\+375(\s+)?\(?(17|29|33|44)\)?(\s+)?[0-9]{3}[0-9]{2}[0-9]{2}$/;
move out of method in global scope. it will be cached vis closure. now you create it every time when you call it.

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  const email = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
move out of method in global scope. it will be cached vis closure. now you create it every time when you call it.

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  const input = /^[A-Za-z][A-Za-z0-9]*$/;
move out of method in global scope. it will be cached vis closure. now you create it every time when you call it.

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  const inputedData = new Date(value).setHours(0, 0, 0, 0);
create separate method for this, follow DRY

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  const now = new Date().setHours(0, 0, 0, 0);
create separate method for this, follow DRY

2021-03-15 20:13 UTC, maximsan commented on src/services/validation.js
> +  return false;
`return inputedData > now || inputedData < 0` - should be the same

2021-03-15 20:13 UTC, maximsan commented on src/services/helpers.js
> +  const datePart = date.match(/\d+/g);
`const [year, month, day] = date.match(/\d+/g)`

2021-03-15 20:13 UTC, maximsan commented on src/services/helpers.js
> +  return today;
inline returned value

2021-03-15 20:13 UTC, maximsan commented on src/pages/Main.jsx
> +          selectItem: this.selectItem,
I definitely skipped it, but it's not good approach. At first split it in several contexts, at second you should keep all data that you pass in context value in variable in closure
`const value = { members, deleteMember: this.deleteMember}`
`<MembersContext.Provider value={value}>{....}</MembersContext.Provider>`

2021-03-16 12:37 UTC, Larkgronick commented on src/App/App.jsx
>        <div>
Changed to empty JSX tags.

2021-03-16 12:37 UTC, Larkgronick commented on src/App/App.jsx
> +          <div>
Changed to empty JSX tags.

2021-03-16 13:56 UTC, Larkgronick commented on src/components/Buttons/Button/Button.scss
> +    // background-color: darken(green, 15%);
Removed comment here.

2021-03-16 13:57 UTC, Larkgronick commented on src/components/Buttons/Button/Button.scss
> +    background-color: darken($dev-color, 15%);
Created $opacity variable and changed here everywhere.

2021-03-16 13:59 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +          <aside className={drawerOpen ? 'side-drawer open' : 'side-drawer'}>
Simplified in this way: 
`className={`side-drawer ${drawerOpen ? 'open' : ''}`}`

2021-03-16 13:59 UTC, Larkgronick commented on src/components/Drawer/DrawerRouter.jsx
> +  return <MainContext.Consumer>{({ userData }) => renderDrawer(userData.role)}</MainContext.Consumer>;
Thanks, changed.

2021-03-16 13:59 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +// import { registerNewUser } from '../../services/services';
Removed.

2021-03-16 14:00 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    const validate = Object.values(validateMembers(data))
Refactored all method here, created and imported helper method.

2021-03-16 14:00 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +      .every((el) => el === false);
Created and replaced here.

2021-03-16 14:01 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    const toValidate = 14;
Created constant variables for number of field validations and imported it here.

2021-03-16 14:03 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    // registerNewUser(email, generateID());  COMMENTED TO PREVENT UNNECESSARY REGISTRATIONS
Add additional info to these comments, i hope now its clear.

2021-03-16 14:03 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    const err = `${name}Err`;
Changed everywhere

2021-03-16 14:03 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +      .every((el) => el === false);
Created and replaced here like in previous case.

2021-03-16 14:05 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const toValidate = 4;
Created and replaced here like in previous case.

2021-03-16 14:05 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const toValidate = 4;
Created constant and replaced here like in previous case.

2021-03-16 14:06 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const status = [...document.querySelectorAll("input[type='checkbox']")].map((el) =>
Created `checkBoxes ` variable and use it once. Also use spread for el. Code looks much better, thanks.

2021-03-16 14:06 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    this.setState((prevState) => ({
Spreaded, thanks.

2021-03-16 14:06 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +          name: userTasks[track].name,
Created name variable, used spread.

2021-03-16 14:07 UTC, Larkgronick commented on src/components/Table/UserTasksTable.jsx
> +      {/* {error
Yes, sure. I dont know how i forget about that...

2021-03-17 13:53 UTC, Larkgronick commented on src/services/helpers.js
> +  return today;
Changed.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  return false;
Thanks, changed. It was written as indian code.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  const now = new Date().setHours(0, 0, 0, 0);
Created methods for this actions: getInputDate and getNow.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  const inputedData = new Date(value).setHours(0, 0, 0, 0);
Created methods for this actions: getInputedDate and getNow.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  const input = /^[A-Za-z][A-Za-z0-9]*$/;
Changed every validation function to function expression.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  const email = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Changed every validation function to function expression.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  const belarusNumber = /^\+375(\s+)?\(?(17|29|33|44)\)?(\s+)?[0-9]{3}[0-9]{2}[0-9]{2}$/;
Changed every validation function to function expression.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  return value.length === 0;
Looks better, replaced.

2021-03-17 13:53 UTC, Larkgronick commented on src/services/validation.js
> +  results.roleErr = validateField('role', role);
Yes, i made proper refactor and all work can be done using one function and looping trough array.

2021-03-17 13:53 UTC, Larkgronick commented on src/pages/Main.jsx
> +      .catch((err) => console.log(err));
Added comments here.

2021-03-17 13:53 UTC, Larkgronick commented on src/pages/Main.jsx
> +    const userDataUpdate = members.filter((el) => el.email === getUserEmail())[0];
Yes, i replaced it.

2021-03-26 15:16 UTC, Larkgronick commented on src/services/helpers.test.jsx
> +});
Made tests refactor.

2021-03-26 15:16 UTC, Larkgronick commented on src/pages/Main.jsx
> +          selectItem: this.selectItem,
I made big changes in whole project, that was tough, but now its look and works much better.

2021-03-27 10:51 UTC, maximsan requested changes
Hello! I left some comments, review please. Good luck!

2021-03-27 10:51 UTC, maximsan commented on src/components/Drawer/Drawer.jsx
> +              if (name === 'My tasks' || name === 'My progress') {
It's a bad approach. Create a Map for this names and use it

2021-03-27 10:51 UTC, maximsan commented on src/components/Drawer/DrawerRouter.jsx
> +      case 'Admin':
It's better to use Map for the roles names too.

2021-03-27 10:51 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
> +    const test = validateCategory('members', data);
rename to validation

2021-03-27 10:51 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +    const checkBoxes = [...document.querySelectorAll("input[type='checkbox']")];
don't use DOM methods

2021-03-27 10:51 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +                                }}
it's the same method. reuse it

2021-03-27 10:51 UTC, maximsan commented on src/components/Table/Table.jsx
> +      case 'members':
create Map for names

2021-03-27 10:51 UTC, maximsan commented on src/components/Table/TaskTrackTable.jsx
> +                          saveTrackData({}, track, getIndex(e), 'delete');
create method

2021-03-27 10:51 UTC, maximsan commented on src/contexts/MainDataProvider.jsx
> +      .catch((err) => console.log(err));
`.catch(console.log)`

2021-03-27 10:51 UTC, maximsan commented on src/contexts/MainDataProvider.jsx
> +    const removed = current.filter((item, index) => index !== getIndex(e));
it's strange that u us index as a value to compare. Does you item not have an id ?

2021-03-27 10:51 UTC, maximsan commented on src/contexts/UserTasksProvider.jsx
> +    const newUserTracks = userTracks;
copy an object here

2021-03-27 10:51 UTC, maximsan commented on src/services/services.js
> +        tasks = tasks.filter((el) => el !== undefined);
`tasks.filter((el) => el)` - should do the same

2021-03-27 10:51 UTC, maximsan commented on src/services/test.js
> +// drawerOpen, drawerToggle //DrawerContext
what is it ? (-_-)

2021-03-27 10:51 UTC, maximsan commented on src/services/validation.js
> +  const input = /^[A-Za-z][A-Za-z0-9]*$/;
Hm, is it a solution ?

2021-03-27 13:05 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    const checkBoxes = [...document.querySelectorAll("input[type='checkbox']")];
Get acess to the DOM using callback refs.

2021-03-27 13:06 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
> +    const test = validateCategory('members', data);
Renamed, thanks.

2021-03-27 13:06 UTC, Larkgronick commented on src/components/Drawer/DrawerRouter.jsx
> +      case 'Admin':
Changed here in this way:
```
    const drawer = {
      Admin: <Drawer>drawerAdmin</Drawer>,
      Mentor: <Drawer>drawerAdmin</Drawer>,
      Member: <Drawer>drawerMember</Drawer>,
    };
    return drawer[role];
  };
```

2021-03-27 13:06 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +              if (name === 'My tasks' || name === 'My progress') {
Changed here in this way:
```
      const openPage = (name) => {
              drawerToggle();
              const page = {
                'My tasks': showUserTasks(),
                'My progress': showUserTasks(),
              };
              return page[name];
            };
```

2021-03-27 13:06 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +                                }}
Made refactor here and removed duplicate.

2021-03-27 13:06 UTC, Larkgronick commented on src/components/Table/Table.jsx
> +      case 'members':
Made refactor, as in previous cases.

2021-03-27 13:07 UTC, Larkgronick commented on src/components/Table/TaskTrackTable.jsx
> +                          saveTrackData({}, track, getIndex(e), 'delete');
Moved to separate method.

2021-03-27 13:07 UTC, Larkgronick commented on src/contexts/MainDataProvider.jsx
> +      .catch((err) => console.log(err));
Beatyfull shorthand, changed.

2021-03-27 13:08 UTC, Larkgronick commented on src/contexts/MainDataProvider.jsx
> +    const removed = current.filter((item, index) => index !== getIndex(e));
Delete function recieves index of clicked field and removed from category by similar index.

2021-03-27 13:08 UTC, Larkgronick commented on src/contexts/UserTasksProvider.jsx
> +    const newUserTracks = userTracks;
Used spread here.

2021-03-27 13:08 UTC, Larkgronick commented on src/services/services.js
> +        tasks = tasks.filter((el) => el !== undefined);
Another shorthand, thanks. Changed.

2021-03-27 13:08 UTC, Larkgronick commented on src/services/test.js
> +// drawerOpen, drawerToggle //DrawerContext
Its my Context Separation plan, forgot to remove it). Deleted.

2021-03-30 17:12 UTC, maximsan approved these changes
Approved!

2021-03-30 17:12 UTC, maximsan commented on src/services/services.js
> +    throw new Error('Error with registration:', error);
`console.error(`Error with registration: ${error}`);`

2021-03-30 17:13 UTC, merged