Feature/hooks redux
Dev-incubator/DIMS.UI-12 pull request #33
Opened 2021-04-05 09:58 UTC by Larkgronick

Request date:
05/04/21

Total:
• Created redux enviroment (store, actions, reducers)
• Removed context and replaced it with redux
• Refactored class managers componennts with functions and hooks
• Fixed styles issues

2021-04-05 21:56 UTC, maximsan requested changes
Hello. I left some comments. Looks promising. Good work!

2021-04-05 21:56 UTC, maximsan commented on src/components/Loader/Spinner.jsx
> +  } = useSelector((state) => state);
select `state.user` if u need just `loading`

2021-04-05 21:56 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +    inputRef = ref;
use `useRef` instead

2021-04-05 21:56 UTC, maximsan commented on src/components/Table/TaskTrackTable.jsx
> +    if (window.confirm('Are you sure you wish to delete this item?')) {
maybe we can use something more nice hear ?

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +      const tasks = await loadUsersData('tasks');
`Promise.all`

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +        payload: { isLogged: true, role, name, lastName, email, members, tasks },
wow, wow, split it, it's a bad approach to pass so many params.. why do u actually need so many things on login ?

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +  console.log(isLight);
remove

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +  };
use ternary operator, u can do `toggleTheme`

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +  const current = category;
u do not copy, it's the same object..

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +  return { type: DELETE_DATA, payload: [field] };
actions should be easy..

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/mainDataAction.js
> +  if (window.confirm('Are you sure you wish to delete this item?')) {
this is not part of an action

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/modalAction.js
> +  }
this action is also overloaded

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/userDataAction.js
> +  };
where is `try catch` and what about hide loader if u get an error ?

2021-04-05 21:56 UTC, maximsan commented on src/store/actions/userDataAction.js
> +  newTrack.userId = userId;
u can add the fields on 29 row

2021-04-05 21:56 UTC, maximsan commented on src/store/reducers/mainDataReducer.js
> +        ...action.payload,
seems like u do the same 4 times, u can simplify it and do 1 time

2021-04-06 12:31 UTC, YauhenKoipish requested changes
looks good

2021-04-06 12:31 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
>    };
```suggestion
  const close = () =>  dispatch(closeEdit());
```

you can use arrow function syntax

2021-04-06 12:31 UTC, YauhenKoipish commented on src/components/Popups/TaskManager.jsx
> +  };
and in other cases too

2021-04-06 12:31 UTC, YauhenKoipish commented on src/components/Popups/TaskTrackManager.jsx
> +  };
look at prev comment

2021-04-07 12:32 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +        return dispatch(showUserTasks());
Made function refactor, removed returns.

2021-04-07 12:32 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +    return () => toggle();
Made function refactor, removed returns.

2021-04-07 12:32 UTC, Larkgronick commented on src/components/Drawer/Drawer.jsx
> +      <div className={`main-page ${drawerOpen ? 'show' : ''}`} onClick={toggle} aria-hidden='true' />
Changed here.

2021-04-07 12:32 UTC, Larkgronick commented on src/components/Drawer/DrawerRouter.jsx
> +  return <div>{renderDrawer(role)}</div>;
Made refactor, DrawerRouter was removed.

2021-04-07 12:32 UTC, Larkgronick commented on src/components/Drawer/DrawerRouter.jsx
> +  } = useSelector((state) => state);
All component was removed.

2021-04-07 12:33 UTC, Larkgronick commented on src/components/Loader/Spinner.jsx
> +  } = useSelector((state) => state);
Thanks, replaced.

2021-04-07 12:33 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    inputRef = ref;
Removed setRef and used inputRef only.

2021-04-07 12:33 UTC, Larkgronick commented on src/components/Table/TaskTrackTable.jsx
> +    if (window.confirm('Are you sure you wish to delete this item?')) {
Yes, i created Confirm component, that shows styled popup, where user can wake his choice.

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +      const tasks = await loadUsersData('tasks');
Implemented Promise all here with await syntax.

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +        payload: { isLogged: true, role, name, lastName, email, members, tasks },
I receive and separate here  data that i need. Made refactor here and pass only payload.

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +  console.log(isLight);
Removed.

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +  };
Thanks, removed indian code and added ternary operator.
`payload: { theme: isLight ? 'light' : 'dark' },`

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +  const current = category;
Removed unnecesary variable.

2021-04-07 12:33 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +  return { type: DELETE_DATA, payload: [field] };
Removed unnecesary variable.

2021-04-07 12:34 UTC, Larkgronick commented on src/store/actions/mainDataAction.js
> +  if (window.confirm('Are you sure you wish to delete this item?')) {
Made refactor after creating Confirm component.

2021-04-07 12:35 UTC, Larkgronick commented on src/store/actions/modalAction.js
> +  }
Edit popup behavior implemented here.

2021-04-07 12:35 UTC, Larkgronick commented on src/store/actions/userDataAction.js
> +  };
Added and implemented try catch behaviour

2021-04-07 12:35 UTC, Larkgronick commented on src/store/actions/userDataAction.js
> +  newTrack.userId = userId;
Replaced.

2021-04-07 12:35 UTC, Larkgronick commented on src/store/reducers/mainDataReducer.js
> +        ...action.payload,
Can you show how i can do this?

2021-04-07 12:36 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
>    };
Thanks, replaced in all cases.

2021-04-07 12:36 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +  };
Thanks, replaced in all cases.

2021-04-07 12:36 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
> +  };
Thanks, replaced in all cases.

2021-04-07 16:39 UTC, maximsan requested changes

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
>          ...data,
why do you sread data? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/TaskTrackManager.jsx
>          ...validation,
why do you sread validation? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
>          ...data,
why you sread data? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
>          ...validation,
why you sread validation? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
>          ...data,
why you sread data? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/components/Popups/MemberManager.jsx
>          ...validation,
why you sread validation? you must to spread `previousState` in this case because in this case you can get old data

2021-04-07 16:39 UTC, maximsan commented on src/store/reducers/mainDataReducer.js
> +        ...action.payload,
easy-peasy..

case SET_THEME:
case LOGIN:
case SWITCH_THEME:
case SAVE_DATA:
   return {  ...state, ...action.payload }

2021-04-07 16:39 UTC, maximsan commented on src/store/reducers/modalReducer.js
> +        ...action.payload,
case SET_THEME:
case  SELECT_ITEM::
case CLOSE_EDIT:
case OPEN_CONFIRM:
   return {  ...state, ...action.payload }

2021-04-07 16:39 UTC, maximsan commented on src/store/actions/userDataAction.js
> +    .catch(console.log);
`console.error` is better I guess

2021-04-07 16:48 UTC, maximsan commented on src/components/Popups/TaskManager.jsx
> +    inputRef = ref;
`useRef` hook?

2021-04-08 07:56 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
> +    inputRef = ref;
Yes, in this way:
` const inputRef = useRef(null);`

2021-04-08 07:59 UTC, Larkgronick commented on src/store/reducers/mainDataReducer.js
> +        ...action.payload,
Of course, its basic switch case feature... I made replacements in repeated reducers.

2021-04-08 08:01 UTC, Larkgronick commented on src/store/reducers/modalReducer.js
> +        ...action.payload,
Thanks, replaced.

2021-04-08 08:04 UTC, Larkgronick commented on src/store/actions/userDataAction.js
> +    .catch(console.log);
Yes, thanks, i changed that.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
>          ...data,
Used previousState instead of data.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/TaskTrackManager.jsx
>          ...validation,
Used previousState instead of data.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
>          ...data,
Used previousState instead of data.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/TaskManager.jsx
>          ...validation,
Used previousState instead of data.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
>          ...data,
Used previousState instead of data.

2021-04-08 08:13 UTC, Larkgronick commented on src/components/Popups/MemberManager.jsx
>          ...validation,
Used previousState instead of data.

2021-04-11 17:57 UTC, maximsan approved these changes
Looks pretty fine) great!

2021-04-12 07:13 UTC, YauhenKoipish approved these changes

2021-04-12 17:58 UTC, merged