Feature/stylization
Dev-incubator/DIMS.UI-12 pull request #34
Opened 2021-04-09 14:30 UTC by Larkgronick

Request date:
09/04/21

Total:
• Implement apaptive behaviour for all pages
• Fixed styles issues
• Add drag & drop feature for members & tasks pages
• Clear console errors

2021-04-13 16:35 UTC, maximsan requested changes

2021-04-13 16:35 UTC, maximsan commented on src/components/Popups/style/Popup.scss
> +    width: 200px;
```
max-width: 200px
width: 100%
``` 
- should be more responsive approach

2021-04-13 16:35 UTC, maximsan commented on src/components/Table/MembersTable.jsx
> +      items.splice(result.destination.index, 0, reorderedItem);
use slice better

2021-04-13 16:35 UTC, maximsan commented on src/pages/styles/Table.scss
> +  .task-tracks-adapt {
make it one name and actually it make sense to create reusable component already styled like this and use only it

2021-04-15 13:54 UTC, Larkgronick commented on src/components/Popups/style/Popup.scss
> +    width: 200px;
Made full refactor in media queries.

2021-04-15 13:54 UTC, Larkgronick commented on src/components/Table/MembersTable.jsx
> +      items.splice(result.destination.index, 0, reorderedItem);
Refactored with slice.

2021-04-15 13:54 UTC, Larkgronick commented on src/pages/styles/Table.scss
> +  .task-tracks-adapt {
Removed unnecesary and repeataple styles, changed components structures.

2021-04-17 15:17 UTC, maximsan approved these changes
I left some comments. Please, check my advices. It's approved.

2021-04-17 15:17 UTC, maximsan commented on src/components/Buttons/Button/Button.scss
> +  font-size: 80%;
it's not recommended, for font size actually you have to use px

2021-04-17 15:17 UTC, maximsan commented on src/components/Table/TasksTable.jsx
> +      updateData(insert, 'tasks');
u can create a reusable method, u have the same code twice. also it's very good, because this logic should be covered with unit tests

2021-04-17 15:17 UTC, maximsan commented on src/pages/Login.jsx
> +          {eggs.map((el) => (
eggs ??? what is it ? ))

2021-04-17 15:20 UTC, YauhenKoipish approved these changes

2021-04-17 16:10 UTC, merged

2021-04-18 07:15 UTC, Larkgronick commented on src/pages/Login.jsx
> +          {eggs.map((el) => (
I show it on the project presentation)

2021-04-18 07:15 UTC, Larkgronick commented on src/components/Table/TasksTable.jsx
> +      updateData(insert, 'tasks');
I created getNewOrder method and moved it to helpers.

2021-04-18 07:15 UTC, Larkgronick commented on src/components/Buttons/Button/Button.scss
> +  font-size: 80%;
Changed to px.